#!/bin/bash

levels=("level1" "level2" "level3" "boss_level")

for level in "$levels"
do
  
  if [ -e "$level1" ]
  then
   
    echo "Creating level"
    mkdir "$level"
 
  else
    echo "level lost"
 
  fi
done
